version: '3.7'
services:
  mongodb:
    container_name: mongoER
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_REPLICA_SET_NAME: ${MONGO_REPLICA_SET_NAME}
    env_file:
        - .env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    command: ["--replSet", "${MONGO_REPLICA_SET_NAME}", "--bind_ip_all"]
    healthcheck:
            test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
            interval: 10s
            start_period: 30s

volumes:
  mongodb_data_container:
